### PR TITLE
john

### PR DESCRIPTION
**Pull request by johnliaogithub**
hello peep. i am cool

### CODE REVIEW

**Comment by johnliaogithub** [comment]
hello i am cool

**Comment by johnliaogithub** [comment]
hello dudes

**Comment by RandomPerson6** [comment]
Excuse **_me**_?_**_**

**Comment by johnliaogithub** [comment]
you're excused!haha

**Comment by RandomPerson6** [comment]
:1st_place_medal:  goes to ME!

**Comment by johnliaogithub** [comment]
i am :100: percent better

**Comment by RandomPerson6** [comment]
NO! NO! NO! I don't like that comment, EW!

**Pull request closed without merging**
